<?php
require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/assets/lang.php'; kp_require_auth();
$map=[
 ['01','Questionnaires','Career Choice + Job Fit','Khetha keeps the NCAP assessment concept and turns it into short, mobile-first flows.','career-quiz.php'],
 ['02','Subject Chooser','Subject Chooser','The learner enters grade, languages, Maths track, subjects, marks and intended careers to explore subject-pathway fit.','subject.php'],
 ['03','Careers','Careers / occupations','Search and filter career options, then open a pathway view with qualifications and alternative routes.','directories.php?tab=careers'],
 ['04','What to Study','Qualifications','Explore qualification level, field, duration and entry requirements.','directories.php?tab=qualifications'],
 ['05','Where to Study','Learning providers','Search providers by type and province and save a preferred provider.','directories.php?tab=providers'],
 ['06','Contact Us','Career Advice','Request human career-practitioner support and keep the request in the learner journey.','contact-advisor.php'],
];
?>
<!doctype html><html lang="<?=kp_lang()?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php include __DIR__.'/assets/pwa-head.php'; ?><title>NCAP Alignment — Khetha Path</title><link rel="stylesheet" href="assets/css/style.css"></head><body><?php include __DIR__.'/assets/navbar.php'; ?><main id="main-content" class="dashboard narrow ncap-page"><p class="eyebrow">NCAP REFERENCE ALIGNMENT</p><h1>Same familiar structure. A more personal journey.</h1><p class="lead">Khetha Path is designed around the core information architecture of the National Career Advice Portal so an existing NCAP user can recognise the main journey.</p><div class="accessibility-note"><b>Source:</b> National Career Advice Portal (NCAP) at ncap.careerhelp.org.za. This prototype uses the NCAP structure as its reference; production content should be synchronised from approved DHET/NCAP data rather than treating local placeholder records as authoritative.</div><div class="ncap-map" style="margin-top:18px"><?php foreach($map as $m):?><article class="ncap-map-card"><span class="num"><?=$m[0]?></span><h3><?=htmlspecialchars($m[1])?></h3><p><b>In Khetha:</b> <?=htmlspecialchars($m[2])?></p><p><?=htmlspecialchars($m[3])?></p><a class="ghost-btn" href="<?=htmlspecialchars($m[4])?>">Open →</a></article><?php endforeach;?></div><section class="panel" style="margin-top:18px"><h2>What Khetha adds beyond the portal structure</h2><div class="three-col"><div><b>🧠 Personalised Journey</b><p class="muted">Profile, assessment results, saved choices and interactions remain connected.</p></div><div><b>🛣️ What If?</b><p class="muted">Explore alternative routes when a first pathway is not available or does not fit the learner's context.</p></div><div><b>🔔 Engagement</b><p class="muted">In-app reminders, saved favourites and optional device notifications keep the next step visible.</p></div></div></section><p style="margin-top:18px"><a href="https://ncap.careerhelp.org.za/" target="_blank" rel="noopener" class="ghost-btn">Open official NCAP ↗</a></p></main></body></html>
