-- Khetha Path — complete local/demo database
-- Import this ONE file in phpMyAdmin > SQL. It creates the database and all tables.
-- The app uses MySQL/MariaDB locally (XAMPP) and can use the same schema in production.

CREATE DATABASE IF NOT EXISTS khetha_path
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE khetha_path;

CREATE TABLE IF NOT EXISTS users (
    userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL DEFAULT '',
    email VARCHAR(190) NOT NULL,
    passwordHash VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(40) NULL,
    grade VARCHAR(30) NULL,
    interests JSON NULL,
    consentAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userID),
    UNIQUE KEY uq_users_email (email),
    KEY idx_users_grade (grade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS careers (
    careerID VARCHAR(120) NOT NULL, title VARCHAR(190) NOT NULL, fieldName VARCHAR(120) NOT NULL, data JSON NOT NULL,
    PRIMARY KEY (careerID), KEY idx_careers_field (fieldName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qualifications (
    qualificationID VARCHAR(120) NOT NULL, title VARCHAR(190) NOT NULL, fieldName VARCHAR(120) NOT NULL, data JSON NOT NULL,
    PRIMARY KEY (qualificationID), KEY idx_qualifications_field (fieldName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS providers (
    providerID VARCHAR(120) NOT NULL, name VARCHAR(190) NOT NULL, providerType VARCHAR(60) NOT NULL, data JSON NOT NULL,
    PRIMARY KEY (providerID), KEY idx_providers_type (providerType)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learner_profiles (
    userID INT UNSIGNED NOT NULL,
    profileData JSON NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userID),
    CONSTRAINT fk_profile_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assessmentResults (
    assessmentID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    source VARCHAR(50) NOT NULL,
    payload JSON NULL,
    derived JSON NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (assessmentID),
    KEY idx_assessment_user_source (userID, source, assessmentID),
    CONSTRAINT fk_assessment_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS favourites (
    favouriteID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    itemType VARCHAR(40) NOT NULL,
    itemID VARCHAR(120) NOT NULL,
    label VARCHAR(190) NOT NULL DEFAULT '',
    metadata JSON NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (favouriteID),
    UNIQUE KEY uq_favourite (userID, itemType, itemID),
    KEY idx_favourite_user (userID, createdAt),
    CONSTRAINT fk_favourite_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
    notificationID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    title VARCHAR(180) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(40) NOT NULL DEFAULT 'journey',
    actionURL VARCHAR(255) NULL,
    scheduledAt DATETIME NULL,
    readAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (notificationID),
    KEY idx_notifications_user (userID, readAt, scheduledAt, createdAt),
    CONSTRAINT fk_notification_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_preferences (
    userID INT UNSIGNED NOT NULL,
    pushEnabled TINYINT(1) NOT NULL DEFAULT 0,
    deadlineReminders TINYINT(1) NOT NULL DEFAULT 1,
    assessmentReminders TINYINT(1) NOT NULL DEFAULT 1,
    journeyTips TINYINT(1) NOT NULL DEFAULT 1,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userID),
    CONSTRAINT fk_notification_pref_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS advisor_requests (
    requestID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    topic VARCHAR(60) NOT NULL,
    note TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'submitted',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (requestID),
    KEY idx_advisor_user (userID, createdAt),
    CONSTRAINT fk_advisor_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_sources (
    sourceID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sourceName VARCHAR(180) NOT NULL,
    sourceURL VARCHAR(500) NULL,
    sourceType VARCHAR(60) NOT NULL DEFAULT 'reference',
    versionLabel VARCHAR(80) NULL,
    approved TINYINT(1) NOT NULL DEFAULT 0,
    lastVerified DATE NULL,
    notes TEXT NULL,
    PRIMARY KEY (sourceID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learner_content_interactions (
    interactionID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    eventType VARCHAR(80) NOT NULL,
    eventData JSON NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (interactionID),
    KEY idx_interaction_user (userID, createdAt),
    CONSTRAINT fk_interaction_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learner_cv_edits (
    userID INT UNSIGNED NOT NULL,
    edits JSON NOT NULL,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userID),
    CONSTRAINT fk_cv_edits_user FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Prototype reference records. Replace/synchronise with approved NCAP/DHET data before production.
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('chemical_engineering','Chemical Engineering','Engineering','{"id":"chemical_engineering","ofo_code":null,"title":"Chemical Engineering","alt_titles":["Process Engineer","Chemical Engineer"],"field":"Engineering","description":"Designs and operates the processes that turn raw materials into everyday products — fuel, plastics, medicine, food.","video_url":null,"riasec":{"R":90,"I":100,"A":10,"S":10,"E":30,"C":40},"work_values":{"achievement":85,"independence":60,"recognition":55,"relationships":40,"support":50,"working_conditions":45},"work_context":{"outdoors":30,"physical":35,"shifts":40,"travel":30,"people":30,"data":80,"things":75,"risk":55},"aptitudes":{"verbal":55,"numerical":90,"spatial":75,"form_perception":65,"clerical_perception":55,"motor_coordination":45,"finger_dexterity":40,"manual_dexterity":40},"math_track":"mathematics","min_aps":34,"tags":["high_demand"],"qualification_ids":["beng_chem"],"demand":"high","salary_band":"R300k – R700k/yr","subject_requirements":[{"subject":"Physical Sciences","min_percent":60,"necessity":"required"},{"subject":"Mathematics","min_percent":60,"necessity":"required"},{"subject":"Life Sciences","min_percent":null,"necessity":"recommended"},{"subject":"Information Technology","min_percent":null,"necessity":"recommended"}],"pathways":["TVET N-courses in Chemical/Process Engineering, then apprenticeship","University bridging/foundation year to strengthen Maths and Physical Sciences","Higher Certificate in Engineering Studies, articulating into a Diploma"],"riasec_code":"IRC"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('medicine','Medicine (MBChB)','Health Sciences','{"id":"medicine","ofo_code":null,"title":"Medicine (MBChB)","alt_titles":["Doctor","Medical Practitioner","Physician"],"field":"Health Sciences","description":"Diagnoses and treats illness and injury as a registered medical doctor, in hospitals, clinics or private practice.","video_url":null,"riasec":{"R":20,"I":100,"A":10,"S":80,"E":30,"C":20},"work_values":{"achievement":90,"independence":55,"recognition":70,"relationships":80,"support":60,"working_conditions":30},"work_context":{"outdoors":5,"physical":40,"shifts":90,"travel":15,"people":95,"data":60,"things":45,"risk":50},"aptitudes":{"verbal":85,"numerical":70,"spatial":55,"form_perception":60,"clerical_perception":55,"motor_coordination":65,"finger_dexterity":60,"manual_dexterity":55},"math_track":"mathematics","min_aps":36,"tags":["high_demand"],"qualification_ids":["mbchb"],"demand":"high","salary_band":"R400k – R1.2m/yr","subject_requirements":[{"subject":"Life Sciences","min_percent":70,"necessity":"required"},{"subject":"Physical Sciences","min_percent":65,"necessity":"required"},{"subject":"Mathematics","min_percent":60,"necessity":"required"}],"pathways":["Higher Certificate/Diploma in a health science (e.g. Nursing, Clinical Technology) with articulation routes","University bridging/foundation year in Health Sciences","Related degree (e.g. BSc Biomedical Science) with postgraduate entry options"],"riasec_code":"ISE"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('actuarial_science','Actuarial Science','Business & Finance','{"id":"actuarial_science","ofo_code":null,"title":"Actuarial Science","alt_titles":["Actuary"],"field":"Business & Finance","description":"Uses statistics and financial theory to measure and manage risk for insurers, pension funds and financial institutions.","video_url":null,"riasec":{"R":10,"I":90,"A":10,"S":10,"E":50,"C":90},"work_values":{"achievement":85,"independence":55,"recognition":60,"relationships":35,"support":40,"working_conditions":65},"work_context":{"outdoors":0,"physical":5,"shifts":5,"travel":10,"people":30,"data":95,"things":10,"risk":5},"aptitudes":{"verbal":60,"numerical":95,"spatial":45,"form_perception":50,"clerical_perception":70,"motor_coordination":25,"finger_dexterity":20,"manual_dexterity":15},"math_track":"mathematics","min_aps":38,"tags":["high_demand"],"qualification_ids":["bsc_actuarial"],"demand":"high","salary_band":"R350k – R900k/yr","subject_requirements":[{"subject":"Mathematics","min_percent":80,"necessity":"required"},{"subject":"Accounting","min_percent":null,"necessity":"recommended"},{"subject":"Physical Sciences","min_percent":null,"necessity":"recommended"}],"pathways":["BCom degree with a strong Maths/Statistics major, then bridge into actuarial exams","Higher Certificate in Financial/Statistical studies, articulating into a BCom"],"riasec_code":"ICE"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('computer_science','Computer Science / Software Development','Information Technology','{"id":"computer_science","ofo_code":null,"title":"Computer Science / Software Development","alt_titles":["Software Developer","Programmer","Software Engineer"],"field":"Information Technology","description":"Designs, builds and maintains the software behind websites, apps and the systems businesses run on.","video_url":null,"riasec":{"R":50,"I":100,"A":20,"S":10,"E":30,"C":50},"work_values":{"achievement":80,"independence":75,"recognition":45,"relationships":35,"support":40,"working_conditions":70},"work_context":{"outdoors":0,"physical":5,"shifts":15,"travel":5,"people":25,"data":95,"things":40,"risk":5},"aptitudes":{"verbal":55,"numerical":80,"spatial":65,"form_perception":60,"clerical_perception":55,"motor_coordination":35,"finger_dexterity":45,"manual_dexterity":20},"math_track":"mathematics","min_aps":30,"tags":["high_demand"],"qualification_ids":["bsc_comp_sci"],"demand":"high","salary_band":"R250k – R800k/yr","subject_requirements":[{"subject":"Mathematics","min_percent":60,"necessity":"required"},{"subject":"Information Technology","min_percent":null,"necessity":"recommended"},{"subject":"Physical Sciences","min_percent":null,"necessity":"recommended"}],"pathways":["TVET National Certificate (Vocational) in IT, then Higher Certificate → Diploma articulation","Private/college Higher Certificate in IT with degree articulation"],"riasec_code":"IRC"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('civil_engineering','Civil Engineering','Engineering','{"id":"civil_engineering","ofo_code":null,"title":"Civil Engineering","alt_titles":["Civil Engineer"],"field":"Engineering","description":"Plans, designs and oversees construction of roads, bridges, water systems and buildings.","video_url":null,"riasec":{"R":100,"I":80,"A":10,"S":10,"E":30,"C":50},"work_values":{"achievement":80,"independence":55,"recognition":55,"relationships":45,"support":45,"working_conditions":35},"work_context":{"outdoors":70,"physical":55,"shifts":30,"travel":50,"people":45,"data":65,"things":80,"risk":60},"aptitudes":{"verbal":50,"numerical":85,"spatial":80,"form_perception":70,"clerical_perception":50,"motor_coordination":45,"finger_dexterity":35,"manual_dexterity":40},"math_track":"mathematics","min_aps":32,"tags":["high_demand"],"qualification_ids":["beng_civil"],"demand":"high","salary_band":"R280k – R650k/yr","subject_requirements":[{"subject":"Physical Sciences","min_percent":55,"necessity":"required"},{"subject":"Mathematics","min_percent":60,"necessity":"required"},{"subject":"Engineering Graphics & Design","min_percent":null,"necessity":"recommended"}],"pathways":["TVET N-courses in Civil Engineering, then apprenticeship toward technologist status","University bridging/foundation year to strengthen Maths and Physical Sciences"],"riasec_code":"RIC"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('chartered_accountancy','Chartered Accountancy (CA(SA))','Business & Finance','{"id":"chartered_accountancy","ofo_code":null,"title":"Chartered Accountancy (CA(SA))","alt_titles":["Chartered Accountant","Accountant"],"field":"Business & Finance","description":"Audits, reports on and advises on the finances of businesses and organisations, registered with SAICA.","video_url":null,"riasec":{"R":10,"I":30,"A":10,"S":20,"E":50,"C":100},"work_values":{"achievement":80,"independence":50,"recognition":55,"relationships":40,"support":45,"working_conditions":55},"work_context":{"outdoors":0,"physical":5,"shifts":20,"travel":15,"people":45,"data":95,"things":5,"risk":5},"aptitudes":{"verbal":60,"numerical":90,"spatial":30,"form_perception":45,"clerical_perception":80,"motor_coordination":20,"finger_dexterity":20,"manual_dexterity":15},"math_track":"mathematics","min_aps":32,"tags":["high_demand"],"qualification_ids":["ca_sa_stream"],"demand":"high","salary_band":"R250k – R700k/yr","subject_requirements":[{"subject":"Mathematics","min_percent":60,"necessity":"required"},{"subject":"Accounting","min_percent":60,"necessity":"required"},{"subject":"Business Studies","min_percent":null,"necessity":"recommended"},{"subject":"Economics","min_percent":null,"necessity":"recommended"}],"pathways":["Higher Certificate in Accounting, articulating into a BCom Accounting Diploma/Degree","National Diploma in Financial Accounting via a university of technology"],"riasec_code":"CEI"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('business_management','Business Management','Business & Finance','{"id":"business_management","ofo_code":null,"title":"Business Management","alt_titles":["Business Manager","Operations Manager"],"field":"Business & Finance","description":"Plans and runs the day-to-day operations of a business or a team within one.","video_url":null,"riasec":{"R":10,"I":20,"A":10,"S":40,"E":100,"C":60},"work_values":{"achievement":75,"independence":60,"recognition":65,"relationships":55,"support":40,"working_conditions":50},"work_context":{"outdoors":5,"physical":10,"shifts":25,"travel":35,"people":80,"data":65,"things":15,"risk":10},"aptitudes":{"verbal":70,"numerical":60,"spatial":30,"form_perception":35,"clerical_perception":55,"motor_coordination":25,"finger_dexterity":20,"manual_dexterity":15},"math_track":"either","min_aps":24,"tags":[],"qualification_ids":["bcom_business_management"],"demand":"medium","salary_band":"R180k – R500k/yr","subject_requirements":[{"subject":"Business Studies","min_percent":null,"necessity":"recommended"},{"subject":"Accounting","min_percent":null,"necessity":"recommended"},{"subject":"Economics","min_percent":null,"necessity":"recommended"},{"subject":"Mathematics","min_percent":null,"necessity":"recommended"}],"pathways":["Higher Certificate in Business/Office Administration, articulating into a Diploma","TVET N-courses in Business Management"],"riasec_code":"ECS"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('law','Law (LLB)','Humanities & Law','{"id":"law","ofo_code":null,"title":"Law (LLB)","alt_titles":["Lawyer","Attorney","Advocate"],"field":"Humanities & Law","description":"Advises on and argues legal matters as an attorney or advocate, after admission to the profession.","video_url":null,"riasec":{"R":10,"I":30,"A":30,"S":60,"E":100,"C":30},"work_values":{"achievement":85,"independence":65,"recognition":70,"relationships":55,"support":40,"working_conditions":35},"work_context":{"outdoors":0,"physical":5,"shifts":20,"travel":20,"people":80,"data":75,"things":5,"risk":10},"aptitudes":{"verbal":90,"numerical":45,"spatial":25,"form_perception":35,"clerical_perception":55,"motor_coordination":15,"finger_dexterity":15,"manual_dexterity":10},"math_track":"either","min_aps":26,"tags":[],"qualification_ids":["llb"],"demand":"medium","salary_band":"R200k – R650k/yr","subject_requirements":[{"subject":"History","min_percent":null,"necessity":"recommended"},{"subject":"Business Studies","min_percent":null,"necessity":"recommended"}],"pathways":["Higher Certificate in Legal Studies/Paralegal Studies, articulating into an LLB","Diploma in Paralegal Studies with progression routes"],"riasec_code":"ESI"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('foundation_phase_teaching','Foundation Phase Teaching','Education','{"id":"foundation_phase_teaching","ofo_code":null,"title":"Foundation Phase Teaching","alt_titles":["Teacher","Educator"],"field":"Education","description":"Teaches Grade R-3 learners the foundational literacy, numeracy and life skills the rest of school builds on.","video_url":null,"riasec":{"R":10,"I":20,"A":50,"S":100,"E":40,"C":30},"work_values":{"achievement":65,"independence":40,"recognition":45,"relationships":90,"support":70,"working_conditions":50},"work_context":{"outdoors":10,"physical":25,"shifts":10,"travel":5,"people":95,"data":30,"things":25,"risk":10},"aptitudes":{"verbal":80,"numerical":45,"spatial":30,"form_perception":35,"clerical_perception":45,"motor_coordination":40,"finger_dexterity":35,"manual_dexterity":30},"math_track":"either","min_aps":24,"tags":["high_demand"],"qualification_ids":["bed_foundation"],"demand":"high","salary_band":"R180k – R380k/yr","subject_requirements":[{"subject":"Life Sciences","min_percent":null,"necessity":"recommended"}],"pathways":["Higher Certificate in Education, articulating into a B.Ed","Diploma in Early Childhood Development with B.Ed articulation"],"riasec_code":"SAE"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('architecture','Architecture','Built Environment','{"id":"architecture","ofo_code":null,"title":"Architecture","alt_titles":["Architect"],"field":"Built Environment","description":"Designs buildings and spaces, balancing function, safety and aesthetics from concept through construction.","video_url":null,"riasec":{"R":60,"I":60,"A":100,"S":10,"E":30,"C":30},"work_values":{"achievement":80,"independence":70,"recognition":60,"relationships":40,"support":40,"working_conditions":45},"work_context":{"outdoors":30,"physical":25,"shifts":20,"travel":30,"people":45,"data":55,"things":65,"risk":20},"aptitudes":{"verbal":55,"numerical":65,"spatial":90,"form_perception":80,"clerical_perception":40,"motor_coordination":45,"finger_dexterity":45,"manual_dexterity":35},"math_track":"mathematics","min_aps":32,"tags":[],"qualification_ids":["barch"],"demand":"medium","salary_band":"R220k – R600k/yr","subject_requirements":[{"subject":"Mathematics","min_percent":60,"necessity":"required"},{"subject":"Engineering Graphics & Design","min_percent":null,"necessity":"recommended"},{"subject":"Visual Arts","min_percent":null,"necessity":"recommended"},{"subject":"Physical Sciences","min_percent":null,"necessity":"recommended"}],"pathways":["National Diploma in Architectural Technology via a university of technology","Higher Certificate in Built Environment studies, articulating into a Diploma"],"riasec_code":"ARI"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('graphic_design','Graphic Design','Creative Arts & Design','{"id":"graphic_design","ofo_code":null,"title":"Graphic Design","alt_titles":["Graphic Designer","Visual Designer"],"field":"Creative Arts & Design","description":"Creates visual content — branding, layouts, digital and print media — for businesses and campaigns.","video_url":null,"riasec":{"R":10,"I":20,"A":100,"S":10,"E":40,"C":20},"work_values":{"achievement":65,"independence":75,"recognition":55,"relationships":35,"support":35,"working_conditions":55},"work_context":{"outdoors":0,"physical":5,"shifts":15,"travel":10,"people":35,"data":45,"things":40,"risk":5},"aptitudes":{"verbal":45,"numerical":35,"spatial":85,"form_perception":85,"clerical_perception":40,"motor_coordination":45,"finger_dexterity":50,"manual_dexterity":30},"math_track":"either","min_aps":null,"tags":[],"qualification_ids":["dip_graphic_design"],"demand":"medium","salary_band":"R150k – R400k/yr","subject_requirements":[{"subject":"Visual Arts","min_percent":50,"necessity":"required"},{"subject":"Information Technology","min_percent":null,"necessity":"recommended"},{"subject":"Engineering Graphics & Design","min_percent":null,"necessity":"recommended"}],"pathways":["TVET/private college Higher Certificate in Graphic Design, articulating into a Diploma","Short courses + a design portfolio route into a Diploma programme"],"riasec_code":"AEI"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('electrician','Electrician (Artisan Trade)','Technical Trades','{"id":"electrician","ofo_code":null,"title":"Electrician (Artisan Trade)","alt_titles":["Electrician"],"field":"Technical Trades","description":"Installs, maintains and repairs electrical wiring and systems in homes, businesses and industry, as a qualified artisan.","video_url":null,"riasec":{"R":100,"I":50,"A":10,"S":10,"E":20,"C":40},"work_values":{"achievement":65,"independence":65,"recognition":40,"relationships":35,"support":40,"working_conditions":30},"work_context":{"outdoors":55,"physical":75,"shifts":40,"travel":45,"people":30,"data":20,"things":95,"risk":75},"aptitudes":{"verbal":35,"numerical":55,"spatial":65,"form_perception":60,"clerical_perception":40,"motor_coordination":80,"finger_dexterity":75,"manual_dexterity":80},"math_track":"either","min_aps":null,"tags":["trade","high_demand"],"qualification_ids":["electrician_trade"],"demand":"high","salary_band":"R150k – R350k/yr","subject_requirements":[{"subject":"Technical Sciences","min_percent":50,"necessity":"required"},{"subject":"Technical Mathematics","min_percent":null,"necessity":"recommended"},{"subject":"Engineering Graphics & Design","min_percent":null,"necessity":"recommended"}],"pathways":["TVET N-courses (N1–N6) in Electrical Engineering, then an apprenticeship and trade test","Direct workplace apprenticeship with block release to a TVET college"],"riasec_code":"RIC"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('agricultural_science','Agricultural Sciences (BSc Agric)','Agriculture','{"id":"agricultural_science","ofo_code":null,"title":"Agricultural Sciences (BSc Agric)","alt_titles":["Agricultural Scientist","Agronomist"],"field":"Agriculture","description":"Applies science to farming and food production — soil, crops, livestock and sustainable land use.","video_url":null,"riasec":{"R":80,"I":90,"A":10,"S":20,"E":30,"C":30},"work_values":{"achievement":70,"independence":65,"recognition":45,"relationships":40,"support":45,"working_conditions":30},"work_context":{"outdoors":85,"physical":60,"shifts":25,"travel":40,"people":35,"data":55,"things":60,"risk":35},"aptitudes":{"verbal":50,"numerical":65,"spatial":45,"form_perception":50,"clerical_perception":45,"motor_coordination":50,"finger_dexterity":40,"manual_dexterity":45},"math_track":"mathematics","min_aps":28,"tags":["green"],"qualification_ids":["bsc_agric"],"demand":"medium","salary_band":"R180k – R450k/yr","subject_requirements":[{"subject":"Agricultural Sciences","min_percent":55,"necessity":"required"},{"subject":"Mathematics","min_percent":50,"necessity":"required"},{"subject":"Life Sciences","min_percent":null,"necessity":"recommended"},{"subject":"Physical Sciences","min_percent":null,"necessity":"recommended"}],"pathways":["National Diploma in Agriculture via a university of technology","Higher Certificate in Agricultural Management, articulating into a Diploma"],"riasec_code":"IRE"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO careers (careerID,title,fieldName,data) VALUES ('journalism_media','Journalism & Media','Humanities & Media','{"id":"journalism_media","ofo_code":null,"title":"Journalism & Media","alt_titles":["Journalist","Reporter"],"field":"Humanities & Media","description":"Researches, writes and produces news and feature content for print, broadcast or digital media.","video_url":null,"riasec":{"R":10,"I":40,"A":90,"S":50,"E":60,"C":20},"work_values":{"achievement":70,"independence":65,"recognition":65,"relationships":55,"support":35,"working_conditions":30},"work_context":{"outdoors":35,"physical":15,"shifts":55,"travel":50,"people":75,"data":60,"things":15,"risk":25},"aptitudes":{"verbal":90,"numerical":40,"spatial":30,"form_perception":35,"clerical_perception":45,"motor_coordination":25,"finger_dexterity":30,"manual_dexterity":15},"math_track":"either","min_aps":24,"tags":[],"qualification_ids":["dip_journalism"],"demand":"medium","salary_band":"R150k – R380k/yr","subject_requirements":[{"subject":"History","min_percent":null,"necessity":"recommended"},{"subject":"Dramatic Arts","min_percent":null,"necessity":"recommended"}],"pathways":["Higher Certificate in Media/Communication Studies, articulating into a Diploma","TVET National Certificate (Vocational) in Media Studies"],"riasec_code":"AES"}' ) ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('beng_chem','BEng Chemical Engineering','Engineering','{"id":"beng_chem","saqa_id":null,"title":"BEng Chemical Engineering","nqf_level":8,"field":"Engineering","entry_requirements":{"aps":34,"subject_minimums":[{"subject":"Mathematics","min_percent":60},{"subject":"Physical Sciences","min_percent":60}]},"duration":"4 years","provider_ids":["uct","wits"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('mbchb','Bachelor of Medicine and Surgery (MBChB)','Health Sciences','{"id":"mbchb","saqa_id":null,"title":"Bachelor of Medicine and Surgery (MBChB)","nqf_level":9,"field":"Health Sciences","entry_requirements":{"aps":36,"subject_minimums":[{"subject":"Life Sciences","min_percent":70},{"subject":"Physical Sciences","min_percent":65}]},"duration":"6 years","provider_ids":["uct","wits"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('bsc_actuarial','BSc Actuarial Science','Business & Finance','{"id":"bsc_actuarial","saqa_id":null,"title":"BSc Actuarial Science","nqf_level":7,"field":"Business & Finance","entry_requirements":{"aps":38,"subject_minimums":[{"subject":"Mathematics","min_percent":80}]},"duration":"3 years","provider_ids":["uct"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('bsc_comp_sci','BSc Computer Science','Information Technology','{"id":"bsc_comp_sci","saqa_id":null,"title":"BSc Computer Science","nqf_level":7,"field":"Information Technology","entry_requirements":{"aps":30,"subject_minimums":[{"subject":"Mathematics","min_percent":60}]},"duration":"3 years","provider_ids":["uct","wits","tut"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('beng_civil','BEng Civil Engineering','Engineering','{"id":"beng_civil","saqa_id":null,"title":"BEng Civil Engineering","nqf_level":8,"field":"Engineering","entry_requirements":{"aps":32,"subject_minimums":[{"subject":"Mathematics","min_percent":60},{"subject":"Physical Sciences","min_percent":55}]},"duration":"4 years","provider_ids":["wits","uct"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('ca_sa_stream','BCom Accounting (CA(SA) stream)','Business & Finance','{"id":"ca_sa_stream","saqa_id":null,"title":"BCom Accounting (CA(SA) stream)","nqf_level":7,"field":"Business & Finance","entry_requirements":{"aps":32,"subject_minimums":[{"subject":"Mathematics","min_percent":60},{"subject":"Accounting","min_percent":60}]},"duration":"3 years","provider_ids":["uct","wits"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('bcom_business_management','BCom Business Management','Business & Finance','{"id":"bcom_business_management","saqa_id":null,"title":"BCom Business Management","nqf_level":7,"field":"Business & Finance","entry_requirements":{"aps":24,"subject_minimums":[]},"duration":"3 years","provider_ids":["uj"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('llb','Bachelor of Laws (LLB)','Humanities & Law','{"id":"llb","saqa_id":null,"title":"Bachelor of Laws (LLB)","nqf_level":8,"field":"Humanities & Law","entry_requirements":{"aps":26,"subject_minimums":[]},"duration":"4 years","provider_ids":["wits","uct"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('bed_foundation','Bachelor of Education (Foundation Phase)','Education','{"id":"bed_foundation","saqa_id":null,"title":"Bachelor of Education (Foundation Phase)","nqf_level":7,"field":"Education","entry_requirements":{"aps":24,"subject_minimums":[]},"duration":"4 years","provider_ids":["uj"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('barch','Bachelor of Architecture','Built Environment','{"id":"barch","saqa_id":null,"title":"Bachelor of Architecture","nqf_level":9,"field":"Built Environment","entry_requirements":{"aps":32,"subject_minimums":[{"subject":"Mathematics","min_percent":60}]},"duration":"5 years","provider_ids":["uct"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('dip_graphic_design','Diploma in Graphic Design','Creative Arts & Design','{"id":"dip_graphic_design","saqa_id":null,"title":"Diploma in Graphic Design","nqf_level":6,"field":"Creative Arts & Design","entry_requirements":{"aps":null,"subject_minimums":[{"subject":"Visual Arts","min_percent":50}]},"duration":"3 years","provider_ids":["tut"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('electrician_trade','N1–N6 Electrical Engineering + Trade Test','Technical Trades','{"id":"electrician_trade","saqa_id":null,"title":"N1–N6 Electrical Engineering + Trade Test","nqf_level":5,"field":"Technical Trades","entry_requirements":{"aps":null,"subject_minimums":[{"subject":"Technical Sciences","min_percent":50}]},"duration":"2–4 years incl. apprenticeship","provider_ids":["central_johannesburg_tvet"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('bsc_agric','BSc Agriculture','Agriculture','{"id":"bsc_agric","saqa_id":null,"title":"BSc Agriculture","nqf_level":7,"field":"Agriculture","entry_requirements":{"aps":28,"subject_minimums":[{"subject":"Mathematics","min_percent":50},{"subject":"Agricultural Sciences","min_percent":55}]},"duration":"4 years","provider_ids":["up"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO qualifications (qualificationID,title,fieldName,data) VALUES ('dip_journalism','Diploma in Journalism','Humanities & Media','{"id":"dip_journalism","saqa_id":null,"title":"Diploma in Journalism","nqf_level":6,"field":"Humanities & Media","entry_requirements":{"aps":24,"subject_minimums":[]},"duration":"3 years","provider_ids":["tut"]}') ON DUPLICATE KEY UPDATE title=VALUES(title),fieldName=VALUES(fieldName),data=VALUES(data);
INSERT INTO providers (providerID,name,providerType,data) VALUES ('uct','University of Cape Town','university','{"id":"uct","name":"University of Cape Town","type":"university","campuses":[{"province":"Western Cape","town":"Cape Town","lat":-33.9577,"lng":18.4612}],"qualification_ids":["beng_chem","mbchb","bsc_actuarial","bsc_comp_sci","beng_civil","ca_sa_stream","llb","barch"],"contact":{"website":"https://www.uct.ac.za","phone":null,"email":null},"nsfas_accredited":true}') ON DUPLICATE KEY UPDATE name=VALUES(name),providerType=VALUES(providerType),data=VALUES(data);
INSERT INTO providers (providerID,name,providerType,data) VALUES ('wits','University of the Witwatersrand','university','{"id":"wits","name":"University of the Witwatersrand","type":"university","campuses":[{"province":"Gauteng","town":"Johannesburg","lat":-26.1929,"lng":28.0305}],"qualification_ids":["beng_chem","mbchb","bsc_comp_sci","beng_civil","ca_sa_stream","llb"],"contact":{"website":"https://www.wits.ac.za","phone":null,"email":null},"nsfas_accredited":true}') ON DUPLICATE KEY UPDATE name=VALUES(name),providerType=VALUES(providerType),data=VALUES(data);
INSERT INTO providers (providerID,name,providerType,data) VALUES ('uj','University of Johannesburg','university','{"id":"uj","name":"University of Johannesburg","type":"university","campuses":[{"province":"Gauteng","town":"Johannesburg","lat":-26.1826,"lng":27.9974}],"qualification_ids":["bcom_business_management","bed_foundation"],"contact":{"website":"https://www.uj.ac.za","phone":null,"email":null},"nsfas_accredited":true}') ON DUPLICATE KEY UPDATE name=VALUES(name),providerType=VALUES(providerType),data=VALUES(data);
INSERT INTO providers (providerID,name,providerType,data) VALUES ('up','University of Pretoria','university','{"id":"up","name":"University of Pretoria","type":"university","campuses":[{"province":"Gauteng","town":"Pretoria","lat":-25.7545,"lng":28.2314}],"qualification_ids":["bsc_agric"],"contact":{"website":"https://www.up.ac.za","phone":null,"email":null},"nsfas_accredited":true}') ON DUPLICATE KEY UPDATE name=VALUES(name),providerType=VALUES(providerType),data=VALUES(data);
INSERT INTO providers (providerID,name,providerType,data) VALUES ('tut','Tshwane University of Technology','university','{"id":"tut","name":"Tshwane University of Technology","type":"university","campuses":[{"province":"Gauteng","town":"Pretoria","lat":-25.7311,"lng":28.1614}],"qualification_ids":["bsc_comp_sci","dip_graphic_design","dip_journalism"],"contact":{"website":"https://www.tut.ac.za","phone":null,"email":null},"nsfas_accredited":true}') ON DUPLICATE KEY UPDATE name=VALUES(name),providerType=VALUES(providerType),data=VALUES(data);
INSERT INTO providers (providerID,name,providerType,data) VALUES ('central_johannesburg_tvet','Central Johannesburg TVET College','tvet','{"id":"central_johannesburg_tvet","name":"Central Johannesburg TVET College","type":"tvet","campuses":[{"province":"Gauteng","town":"Johannesburg","lat":-26.2041,"lng":28.0473}],"qualification_ids":["electrician_trade"],"contact":{"website":"https://www.cjc.edu.za","phone":null,"email":null},"nsfas_accredited":true}') ON DUPLICATE KEY UPDATE name=VALUES(name),providerType=VALUES(providerType),data=VALUES(data);

INSERT INTO content_sources (sourceName, sourceURL, sourceType, versionLabel, approved, lastVerified, notes)
SELECT 'National Career Advice Portal (NCAP)', 'https://ncap.careerhelp.org.za/', 'government-reference', 'reference', 1, CURDATE(), 'Reference source for Khetha Path information architecture. Production data should be synchronised through an approved DHET/NCAP integration.'
WHERE NOT EXISTS (SELECT 1 FROM content_sources WHERE sourceName = 'National Career Advice Portal (NCAP)');

INSERT INTO content_sources (sourceName, sourceURL, sourceType, versionLabel, approved, lastVerified, notes)
SELECT 'DHET Career Development Services / Khetha', 'https://ncap.careerhelp.org.za/', 'government-reference', 'reference', 1, CURDATE(), 'Government programme reference. Keep production content traceable to approved sources.'
WHERE NOT EXISTS (SELECT 1 FROM content_sources WHERE sourceName = 'DHET Career Development Services / Khetha');
