-- OBSOLETE MIGRATION
-- The final Khetha Path build now includes learner_cv_edits, interests and all
-- supporting tables in database/khetha_path.sql. Import that ONE file instead.
-- Do not run this migration against a fresh database.
